### ISSUE TITLE
Validating an undefined property will cause an error

### ISSUE THREAD

**Issue by lucapinelli** [oussamahamdaoui/forgJs#70] opened 2019-03-18 15:26 UTC
Validating an undefined property will cause an error, e.g.:

```js

const { Validator, Rule } = require('@cesium133/forgjs');


let validator = new Validator({
    name: new Rule({ type: 'string', optional: false, notEmpty: true, minLength: 1 }),
});

// this will works
validator.test({ name: 'ok' }); // return true


// this will throw an exception
validator.test({ name: null }); // this throw an Error

```

(I'm using @cesium133/forgjs version "1.1.9)

**Comment by XX-NF-XX** [comment] 2019-03-18 19:20
This is duplicate of #66 
PR #67 should resolve this

**Closed** 2019-03-25 07:59 UTC
